"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Files, Upload } from "lucide-react";
import styles from "./bulk-upload.module.css";
type Site={id:string;name:string};type ObjectItem={id:string;name:string};
export default function BulkUpload({projectSlug,sites,objects}:{projectSlug:string;sites:Site[];objects:ObjectItem[]}){
  const router=useRouter();const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function submit(form:HTMLFormElement){setBusy(true);setMessage("");try{const fd=new FormData(form);files.forEach((file)=>fd.append("files",file));const response=await fetch("/api/catalog/bulk",{method:"POST",body:fd});const payload=await response.json() as {error?:string;count?:number};if(!response.ok)throw new Error(payload.error||"Bulk upload failed.");setMessage(`${payload.count||files.length} files added to the Catalog.`);setFiles([]);form.reset();router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Bulk upload failed.");}finally{setBusy(false);}}
  return <details className={styles.box}><summary><Files size={16}/> Bulk add photos & documents</summary><form onSubmit={(e)=>{e.preventDefault();void submit(e.currentTarget);}}><input type="hidden" name="projectSlug" value={projectSlug}/><label><span>Files</span><input type="file" multiple accept="image/*,.pdf,.doc,.docx,.txt,.csv,.xlsx" onChange={(e)=>setFiles(Array.from(e.target.files||[]).slice(0,12))}/><small>{files.length?`${files.length} selected`:`Up to 12 files, max 20 MB each.`}</small></label><label><span>Site</span><select name="siteId"><option value="">No site</option>{sites.map((site)=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label><span>Object / area</span><select name="physicalObjectId"><option value="">Link later</option>{objects.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Visibility</span><select name="visibility" defaultValue="project"><option>private</option><option>project</option><option>public</option></select></label><label className={styles.wide}><span>Shared note</span><input name="description" placeholder="Optional note applied to every file"/></label><button disabled={!files.length||busy}><Upload size={15}/>{busy?"Uploading...":"Upload batch"}</button>{message?<p>{message}</p>:null}</form></details>;
}
