import Link from "next/link";
import { Camera, FileText, Mic, Pencil, Plus, Search, Shield, Users } from "lucide-react";
import AppShell from "@/components/app-shell";
import BulkUpload from "@/components/bulk-upload";
import { requireCurrentUser } from "@/lib/current-user";
import { listCatalogRecords, listObjectsForProject, listProjectsForUser, listSitesForProject } from "@/lib/records";
import { signedAssetUrl } from "@/lib/r2";
import { createRecordAction } from "./actions";

export const dynamic = "force-dynamic";
function recordIcon(type:string){if(type==="photo")return Camera;if(type==="voice")return Mic;return FileText;}

export default async function CatalogPage({searchParams}:{searchParams:Promise<{project?:string;q?:string;type?:string;context?:string}>}){
  const user=await requireCurrentUser();const params=await searchParams;const projects=await listProjectsForUser(user.localUserId);
  const selectedProject=projects.find((project)=>project.slug===params.project)||projects.find((project)=>project.slug==="casignana")||projects[0];
  if(!selectedProject)throw new Error("Create a project before adding catalog records.");
  const [allRecords,sitesRaw,objectsRaw]=await Promise.all([listCatalogRecords(selectedProject.id,user.localUserId),listSitesForProject(selectedProject.id),listObjectsForProject(selectedProject.id)]);
  const query=(params.q||"").trim().toLowerCase();const type=(params.type||"").trim();const context=(params.context||"").trim();
  const records=allRecords.filter((record)=>{
    if(type&&record.recordType!==type)return false;
    if(context&&record.siteId!==context&&record.physicalObjectId!==context)return false;
    if(!query)return true;
    return [record.title,record.description,record.additionalInformation,record.filterName,record.enhancement,record.authorName,record.authorEmail,record.siteName,record.objectName,record.recordType].some((value)=>value?.toLowerCase().includes(query));
  });
  const previews=new Map<string,string>();await Promise.all(records.map(async(record)=>{if(record.assetR2Key&&record.assetMimeType?.startsWith("image/"))previews.set(record.id,await signedAssetUrl(record.assetR2Key,600));}));
  const sites=sitesRaw.map((item)=>({id:String(item.id),name:String(item.name)}));const objects=objectsRaw.map((item)=>({id:String(item.id),name:String(item.name)}));
  const types=Array.from(new Set(allRecords.map((record)=>record.recordType))).sort();

  return <AppShell user={user} active="Catalog">
    <header className="workspace-header catalog-header"><div><p className="eyebrow">{selectedProject.name} · pilot workspace</p><h1>Catalog</h1><p>Evidence overview for notes, photographs, documents, conditions, interventions and spatial observations.</p></div><div className="header-stat"><strong>{records.length}</strong><span>of {allRecords.length} visible records</span></div></header>
    {projects.length>1?<nav className="project-switcher" aria-label="Catalog project">{projects.map((project)=><Link className={project.id===selectedProject.id?"active":""} href={`/catalog?project=${encodeURIComponent(project.slug)}`} key={project.id}>{project.name}</Link>)}</nav>:null}

    <form className="search-form catalog-filter"><input type="hidden" name="project" value={selectedProject.slug}/><Search size={17}/><input name="q" defaultValue={params.q||""} placeholder="Search title, description, author, context..."/><select name="type" defaultValue={type}><option value="">All types</option>{types.map((item)=><option key={item} value={item}>{item}</option>)}</select><select name="context" defaultValue={context}><option value="">All contexts</option>{sites.map((site)=><option key={`s-${site.id}`} value={site.id}>Site: {site.name}</option>)}{objects.map((item)=><option key={`o-${item.id}`} value={item.id}>Object: {item.name}</option>)}</select><button>Filter</button>{query||type||context?<Link href={`/catalog?project=${encodeURIComponent(selectedProject.slug)}`}>Clear</Link>:null}</form>

    <BulkUpload projectSlug={selectedProject.slug} sites={sites} objects={objects}/>

    <section className="quick-add-panel"><div className="panel-heading"><div><p className="eyebrow">Capture</p><h2>Add a record</h2></div><p>Capture now and refine later. Conditions and interventions use the dedicated Conservation workspace.</p></div>
      <form action={createRecordAction} className="record-form"><input type="hidden" name="projectSlug" value={selectedProject.slug}/><label><span>Type</span><select name="recordType" defaultValue="note"><option value="note">Note</option><option value="photo">Photo</option><option value="document">Document</option><option value="observation">Observation</option><option value="measurement">Measurement</option><option value="voice">Voice</option></select></label><label><span>Visibility</span><select name="visibility" defaultValue="project"><option value="private">Private</option><option value="project">Project</option><option value="public">Public</option></select></label><label><span>Acquisition date</span><input type="datetime-local" name="acquisitionAt"/><small>Leave empty to use capture time.</small></label><label><span>Site</span><select name="siteId"><option value="">No site</option>{sites.map((site)=><option value={site.id} key={site.id}>{site.name}</option>)}</select></label><label><span>Physical object</span><select name="physicalObjectId"><option value="">Link later</option>{objects.map((object)=><option value={object.id} key={object.id}>{object.name}</option>)}</select></label><label className="wide"><span>Title</span><input name="title" placeholder="Optional short title"/></label><label className="wide"><span>Description / note</span><textarea name="description" rows={3} placeholder="What did you observe?"/></label><label><span>Filter</span><input name="filterName" placeholder="Visible, UV, IR..."/></label><label><span>Enhancement</span><input name="enhancement" placeholder="None, inverted..."/></label><label className="wide"><span>Additional information</span><input name="additionalInformation" placeholder="Optional catalog remarks"/></label><label className="wide file-field"><span>Photo or document</span><input type="file" name="file" accept="image/*,.pdf,.doc,.docx,.txt,.csv,.xlsx"/></label><button className="primary-button" type="submit"><Plus size={16}/> Save record</button></form><p className="form-note"><Shield size={13}/> Private records remain visible only to their author. External anonymous publishing remains disabled during the pilot.</p>
    </section>

    <section className="catalog-section"><div className="panel-heading"><div><p className="eyebrow">Evidence overview</p><h2>Records</h2></div><p><Users size={14}/> Authors and project owners/admins can edit metadata. Original files and authorship remain preserved.</p></div>
      {records.length?<><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>ID</th><th>Preview</th><th>Type</th><th>Description</th><th>Acquisition</th><th>Author</th><th>Visibility</th><th>Context</th><th>Status</th><th></th></tr></thead><tbody>{records.map((record)=>{const Icon=recordIcon(record.recordType);const preview=previews.get(record.id);return <tr key={record.id}><td><Link href={`/records/${record.id}`} className="record-id">{record.id.slice(0,8)}</Link></td><td>{preview?<img className="record-thumb" src={preview} alt=""/>:<span className="record-placeholder"><Icon size={17}/></span>}</td><td>{record.recordType}</td><td><Link href={`/records/${record.id}`} className="record-title">{record.title||record.description||"Untitled record"}</Link></td><td>{new Date(record.acquisitionAt).toLocaleDateString("en-GB")}</td><td>{record.authorName||record.authorEmail}</td><td><span className={`visibility-badge ${record.visibility}`}>{record.visibility}</span></td><td>{record.objectName||record.siteName||"Unlinked"}</td><td>{record.status}</td><td>{record.canEdit?<Link className="icon-action" href={`/records/${record.id}/edit`} title="Edit record"><Pencil size={14}/></Link>:null}</td></tr>})}</tbody></table></div><div className="catalog-cards">{records.map((record)=>{const Icon=recordIcon(record.recordType);const preview=previews.get(record.id);return <article className="catalog-card" key={record.id}><Link href={`/records/${record.id}`} className="catalog-card-main">{preview?<img src={preview} alt=""/>:<div className="catalog-card-placeholder"><Icon size={22}/></div>}<div><span className="catalog-meta">{record.recordType} · {new Date(record.acquisitionAt).toLocaleDateString("en-GB")}</span><strong>{record.title||record.description||"Untitled record"}</strong><p>{record.objectName||record.siteName||"Not linked yet"}</p><span className={`visibility-badge ${record.visibility}`}>{record.visibility}</span></div></Link>{record.canEdit?<Link className="catalog-card-edit" href={`/records/${record.id}/edit`}><Pencil size={14}/> Edit</Link>:null}</article>})}</div></>:<div className="empty-state"><h3>No matching records</h3><p>Change the filters or add evidence for {selectedProject.name}.</p></div>}
    </section>
  </AppShell>;
}
